[libraries]
bignum = "com.ionspin.kotlin:bignum:0.3.10"
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
kotlinx-atomicfu = "org.jetbrains.kotlinx:atomicfu:0.30.0-beta"
